"""Apply generated run artifacts to a project root with a durable manifest."""

from __future__ import annotations

import json
import re
import subprocess
from dataclasses import asdict, dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

import yaml

from local_engine.artifacts.patch_collector import extract_diffs
from local_engine.runtime.apply_snapshot import ApplySnapshot
from local_engine.runtime.artifact_parsing import (
    ARTIFACT_PROTOCOL_VERSION,
    FileArtifact,
    artifacts_from_sip_list,
    clean_path,
    parse_file_blocks,
)
from local_engine.runtime.verification import VerificationResult, VerificationStatus, run_verification
from local_engine.safety.patch_validator import validate_patch_set
from local_engine.safety.permission_guard import is_safe_project_relative, validate_project_root

_PATCH_PATH = re.compile(r"^\+\+\+\s+(?:b/)?(.+)$", re.MULTILINE)

__all__ = [
    "ARTIFACT_PROTOCOL_VERSION",
    "ApplyResult",
    "ArtifactApplier",
    "DeliveryStatus",
    "FileArtifact",
    "VerificationResult",
    "VerificationStatus",
]


class DeliveryStatus(str, Enum):
    NOT_STARTED = "not_started"
    PLAN_ONLY = "plan_only"
    ARTIFACTS_GENERATED = "artifacts_generated"
    APPLIED = "applied"
    VERIFIED = "verified"
    FAILED = "failed"
    NEEDS_HUMAN = "needs_human"


@dataclass
class ApplyResult:
    run_id: str
    project_root: str
    run_dir: str
    delivery_status: str = DeliveryStatus.NOT_STARTED.value
    applied_to_project: bool = False
    verification_status: str = VerificationStatus.NOT_RUN.value
    verification_command: List[str] = field(default_factory=list)
    verification_exit_code: Optional[int] = None
    files_created: List[str] = field(default_factory=list)
    files_modified: List[str] = field(default_factory=list)
    files_unchanged: List[str] = field(default_factory=list)
    files_not_applied: List[str] = field(default_factory=list)
    patches_applied: List[str] = field(default_factory=list)
    generated_files: List[str] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    manifest_path: str = ""
    requires_apply: bool = False
    user_goal_satisfied: bool = False
    artifact_protocol: str = ARTIFACT_PROTOCOL_VERSION

    def to_dict(self, **overrides: Any) -> Dict[str, Any]:
        payload = asdict(self)
        payload.update(overrides)
        return payload


class ArtifactApplier:
    """Collect and apply project-local file artifacts generated by a run."""

    def __init__(self, project_root: Path, run_dir: Path) -> None:
        self.project_root = validate_project_root(project_root)
        self.run_dir = Path(run_dir).expanduser().resolve()
        if not self.run_dir.is_dir():
            raise FileNotFoundError("run directory does not exist: {0}".format(self.run_dir))
        self.agent_outputs_dir = self.run_dir / "agent_outputs"
        self.patches_dir = self.run_dir / "patches"
        self.manifest_path = self.run_dir / "apply_manifest.json"
        self.graph = self._load_graph()

    def collect_artifacts(self) -> List[FileArtifact]:
        """Extract file blocks and SIP-declared file artifacts from candidate task outputs."""
        task_ids = self._candidate_task_ids()
        collected: Dict[str, FileArtifact] = {}
        warnings: List[str] = []
        for task_id in task_ids:
            sip, raw = self._read_task_output(task_id)
            source = "agent_outputs/{0}".format(task_id)
            explicit = artifacts_from_sip_list(
                sip.get("artifacts"),
                source,
                protocol=str(sip.get("artifact_protocol") or ""),
            )
            for artifact in explicit:
                self._add_artifact(collected, artifact, warnings)
            if explicit:
                continue
            body = str(sip.get("body") or "")
            for artifact in parse_file_blocks(body, source + ".sip.body"):
                self._add_artifact(collected, artifact, warnings)
            if raw and raw != body:
                for artifact in parse_file_blocks(raw, source + ".raw"):
                    self._add_artifact(collected, artifact, warnings)
        return list(collected.values())

    def collect_patch_paths(self, explicit_paths: Optional[Iterable[Path]] = None) -> List[Path]:
        """Return existing patch files plus diff blocks extracted from run outputs."""
        self.patches_dir.mkdir(parents=True, exist_ok=True)
        paths = [Path(path) for path in (explicit_paths or []) if Path(path).is_file()]
        known = {path.resolve() for path in paths}
        for existing in sorted(self.patches_dir.glob("*.patch")):
            resolved = existing.resolve()
            if resolved not in known:
                paths.append(existing)
                known.add(resolved)
        for task_id in self._candidate_task_ids():
            sip, raw = self._read_task_output(task_id)
            blocks: List[str] = []
            blocks.extend(extract_diffs(str(sip.get("body") or "")))
            blocks.extend(extract_diffs(raw))
            if not blocks:
                continue
            path = self.patches_dir / "{0}.patch".format(task_id)
            if path.resolve() not in known:
                path.write_text("\n".join(blocks), encoding="utf-8")
                paths.append(path)
                known.add(path.resolve())
        return paths

    def dry_run(self, mode: str = "apply", patch_paths: Optional[Iterable[Path]] = None) -> ApplyResult:
        """Collect and validate applyable artifacts without mutating project files."""
        result = ApplyResult(
            run_id=self.run_dir.name,
            project_root=str(self.project_root),
            run_dir=str(self.run_dir),
            manifest_path=str(self.manifest_path),
            requires_apply=self.requires_apply(),
        )
        try:
            files = self.collect_artifacts()
            patches = self.collect_patch_paths(patch_paths)
            for artifact in files:
                self._validate_relative_path(artifact.relative_path)
            if patches:
                validate_patch_set(path.read_text(encoding="utf-8") for path in patches)
                for patch in patches:
                    self._patch_targets(patch)
        except Exception as exc:
            result.delivery_status = DeliveryStatus.FAILED.value
            result.errors.append(str(exc))
            self.write_manifest(result)
            return result
        result.generated_files = [artifact.relative_path for artifact in files]
        result.files_not_applied = list(result.generated_files)
        if mode == "plan":
            result.delivery_status = DeliveryStatus.PLAN_ONLY.value
        elif result.requires_apply and (files or patches):
            result.delivery_status = DeliveryStatus.ARTIFACTS_GENERATED.value
        elif result.requires_apply:
            result.delivery_status = DeliveryStatus.ARTIFACTS_GENERATED.value
            result.warnings.append("applyable tasks completed, but no file blocks or patch blocks were found")
        else:
            result.delivery_status = DeliveryStatus.NOT_STARTED.value
        self.write_manifest(result)
        return result

    def apply(
        self,
        approved: bool,
        mode: str = "apply",
        patch_paths: Optional[Iterable[Path]] = None,
        verify: bool = True,
    ) -> ApplyResult:
        """Apply collected patches/file blocks, preserving a manifest even on failure."""
        result = ApplyResult(
            run_id=self.run_dir.name,
            project_root=str(self.project_root),
            run_dir=str(self.run_dir),
            manifest_path=str(self.manifest_path),
            requires_apply=self.requires_apply(),
        )
        try:
            files = self.collect_artifacts()
            patches = self.collect_patch_paths(patch_paths)
        except Exception as exc:
            result.delivery_status = DeliveryStatus.FAILED.value
            result.errors.append(str(exc))
            self.write_manifest(result)
            return result
        result.generated_files = [artifact.relative_path for artifact in files]
        result.files_not_applied = [artifact.relative_path for artifact in files]
        if mode == "plan":
            result.delivery_status = DeliveryStatus.PLAN_ONLY.value
            self.write_manifest(result)
            return result
        if not result.requires_apply:
            result.delivery_status = DeliveryStatus.NOT_STARTED.value
            self.write_manifest(result)
            return result
        if not files and not patches:
            result.delivery_status = DeliveryStatus.ARTIFACTS_GENERATED.value
            result.warnings.append("applyable tasks completed, but no file blocks or patch blocks were found")
            self.write_manifest(result)
            return result

        result.delivery_status = DeliveryStatus.ARTIFACTS_GENERATED.value
        self.write_manifest(result)
        if not approved:
            result.delivery_status = DeliveryStatus.NEEDS_HUMAN.value
            result.warnings.append("apply approval was not granted; generated artifacts were left in the run directory")
            self.write_manifest(result)
            return result

        try:
            patch_targets = self._preflight(files, patches)
        except Exception as exc:
            result.delivery_status = DeliveryStatus.FAILED.value
            result.errors.append(str(exc))
            result.warnings.append("preflight validation failed; no project files were modified")
            self.write_manifest(result)
            return result

        snapshot = ApplySnapshot(self.project_root)
        snapshot.capture([artifact.relative_path for artifact in files])
        snapshot.capture(path for targets in patch_targets.values() for path in targets)
        try:
            self._apply_patches(patches, result)
            self._write_files(files, result)
            result.files_not_applied = []
            result.applied_to_project = bool(result.files_created or result.files_modified or result.files_unchanged or result.patches_applied)
            result.delivery_status = DeliveryStatus.APPLIED.value if result.applied_to_project else DeliveryStatus.ARTIFACTS_GENERATED.value
            if result.applied_to_project and verify:
                verification = run_verification(self.project_root)
                result.verification_status = verification.status
                result.verification_command = verification.command
                result.verification_exit_code = verification.exit_code
                if verification.output:
                    result.warnings.append("verification output: {0}".format(_truncate(verification.output, 1200)))
                if verification.status == VerificationStatus.PASSED.value:
                    result.delivery_status = DeliveryStatus.VERIFIED.value
                elif verification.status in {VerificationStatus.FAILED.value, VerificationStatus.ERROR.value}:
                    result.delivery_status = DeliveryStatus.FAILED.value
                    result.errors.append("verification failed")
            self.write_manifest(result)
            return result
        except Exception as exc:
            result.delivery_status = DeliveryStatus.FAILED.value
            result.errors.append(str(exc))
            unrestored = snapshot.restore()
            result.files_created, result.files_modified, result.files_unchanged = [], [], []
            result.patches_applied = []
            result.applied_to_project = False
            result.files_not_applied = list(result.generated_files)
            if unrestored:
                result.errors.append("rollback could not restore: {0}".format(", ".join(unrestored)))
            else:
                result.warnings.append("apply failed; project files were restored to their prior state")
            self.write_manifest(result)
            return result

    def write_manifest(self, result: ApplyResult) -> Path:
        self.manifest_path.write_text(json.dumps(result.to_dict(), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        return self.manifest_path

    def requires_apply(self) -> bool:
        for task in self.graph.get("tasks", []):
            expected = task.get("expected_output", {}) if isinstance(task.get("expected_output"), dict) else {}
            if expected.get("type") == "patch":
                return True
            if "code_change" in {str(value) for value in task.get("risk_tags", [])}:
                return True
            if str(task.get("task_type", "")) in {"code_generation", "test_generation", "fix"}:
                return True
        return False

    def _load_graph(self) -> Dict[str, Any]:
        try:
            value = yaml.safe_load((self.run_dir / "task_graph.yaml").read_text(encoding="utf-8"))
        except (OSError, yaml.YAMLError):
            return {}
        return value if isinstance(value, dict) else {}

    def _candidate_task_ids(self) -> List[str]:
        tasks = self.graph.get("tasks") if isinstance(self.graph.get("tasks"), list) else []
        if not tasks:
            return sorted(path.stem.replace(".sip", "") for path in self.agent_outputs_dir.glob("*.sip.yaml"))
        candidates = []
        for task in tasks:
            if not isinstance(task, dict) or not task.get("id"):
                continue
            expected = task.get("expected_output", {}) if isinstance(task.get("expected_output"), dict) else {}
            if (
                expected.get("type") == "patch"
                or "code_change" in {str(value) for value in task.get("risk_tags", [])}
                or str(task.get("task_type", "")) in {"code_generation", "test_generation", "fix"}
                or str(task.get("skill", "")) in {"generate_code", "test_generation", "fix_code", "backend", "frontend"}
            ):
                candidates.append(str(task["id"]))
        return candidates

    def _read_task_output(self, task_id: str) -> Tuple[Dict[str, Any], str]:
        sip: Dict[str, Any] = {}
        try:
            value = yaml.safe_load((self.agent_outputs_dir / "{0}.sip.yaml".format(task_id)).read_text(encoding="utf-8"))
            if isinstance(value, dict):
                sip = value
        except (OSError, yaml.YAMLError):
            sip = {}
        try:
            raw = (self.agent_outputs_dir / "{0}.raw.txt".format(task_id)).read_text(encoding="utf-8")
        except OSError:
            raw = ""
        return sip, raw

    def _add_artifact(self, collected: Dict[str, FileArtifact], artifact: FileArtifact, warnings: List[str]) -> None:
        relative = self._validate_relative_path(artifact.relative_path)
        artifact.relative_path = relative
        previous = collected.get(relative)
        if previous and previous.content != artifact.content:
            warnings.append("multiple generated artifacts targeted `{0}`; using latest from {1}".format(relative, artifact.source))
        collected[relative] = artifact

    def _validate_relative_path(self, path_value: str) -> str:
        value = clean_path(path_value)
        path = Path(value)
        if path.is_absolute():
            resolved = path.expanduser().resolve()
            try:
                value = resolved.relative_to(self.project_root).as_posix()
            except ValueError:
                raise PermissionError("artifact path is outside the project root: {0}".format(path_value)) from None
        if not is_safe_project_relative(value):
            raise PermissionError("artifact path is unsafe: {0}".format(path_value))
        target = (self.project_root / value).resolve()
        try:
            resolved_relative = target.relative_to(self.project_root)
        except ValueError:
            raise PermissionError("artifact path escapes the project root: {0}".format(path_value)) from None
        if not is_safe_project_relative(resolved_relative.as_posix()):
            raise PermissionError("artifact path resolves into a protected location: {0}".format(path_value))
        return Path(value).as_posix()

    def _write_files(self, files: List[FileArtifact], result: ApplyResult) -> None:
        for artifact in files:
            relative = self._validate_relative_path(artifact.relative_path)
            target = (self.project_root / relative).resolve()
            existed = target.exists()
            previous = target.read_text(encoding="utf-8") if existed and target.is_file() else None
            target.parent.mkdir(parents=True, exist_ok=True)
            if previous == artifact.content:
                result.files_unchanged.append(relative)
                continue
            target.write_text(artifact.content, encoding="utf-8")
            if existed:
                result.files_modified.append(relative)
            else:
                result.files_created.append(relative)

    def _preflight(self, files: List[FileArtifact], patch_paths: List[Path]) -> Dict[Path, List[str]]:
        """Validate every path and patch before anything is written; return patch targets by patch."""
        for artifact in files:
            artifact.relative_path = self._validate_relative_path(artifact.relative_path)
        if not patch_paths:
            return {}
        validate_patch_set(path.read_text(encoding="utf-8") for path in patch_paths)
        targets = {patch_path: self._patch_targets(patch_path) for patch_path in patch_paths}
        for patch_path in patch_paths:
            checked = subprocess.run(
                ["git", "apply", "--check", str(patch_path)],
                cwd=str(self.project_root),
                text=True,
                capture_output=True,
                check=False,
            )
            if checked.returncode != 0:
                raise ValueError("patch failed safety check {0}: {1}".format(patch_path.name, checked.stderr.strip()))
        return targets

    def _apply_patches(self, patch_paths: List[Path], result: ApplyResult) -> None:
        for patch_path in patch_paths:
            targets = self._patch_targets(patch_path)
            existed = {path: (self.project_root / path).exists() for path in targets}
            applied = subprocess.run(
                ["git", "apply", str(patch_path)],
                cwd=str(self.project_root),
                text=True,
                capture_output=True,
                check=False,
            )
            if applied.returncode != 0:
                raise RuntimeError("patch application failed {0}: {1}".format(patch_path.name, applied.stderr.strip()))
            result.patches_applied.append(patch_path.name)
            for relative in targets:
                if existed.get(relative):
                    result.files_modified.append(relative)
                else:
                    result.files_created.append(relative)

    def _patch_targets(self, patch_path: Path) -> List[str]:
        text = patch_path.read_text(encoding="utf-8")
        targets = []
        for raw in _PATCH_PATH.findall(text):
            if raw == "/dev/null":
                continue
            relative = self._validate_relative_path(raw)
            targets.append(relative)
        return list(dict.fromkeys(targets))


def _truncate(text: str, limit: int) -> str:
    value = text.strip()
    return value if len(value) <= limit else value[:limit] + "\n[truncated]"
